### ISSUE TITLE
[Connect UC ] Add support for Multiple examples

### ISSUE THREAD

**Issue by eleonoraortega** [mulesoft-labs/rajapa#27]
The raml that is going to be presented in the Connect uses Multiple examples, which is a feature of RAML 1.0

https://github.com/raml-org/raml-examples/blob/master/others/mobile-order-api/api.raml

In this case, is not correctly parsed the following part:

``` yaml
examples:
              single-order:
                orders:
                  -
                    order_id: "ORDER-437563756"
                    creation_date: "2016-03-30"
                    items:
                      -
                        product_id: "PRODUCT-1"
                        quantity: 5
                      -
                        product_id: "PRODUCT-2"
                        quantity: 2
                multiple-orders:
                  orders:
                    -
                      order_id: "ORDER-437563756"
                      creation_date: "2016-03-30"
                      items:
                        -
                          product_id: "PRODUCT-1"
                          quantity: 5
                        -
                          product_id: "PRODUCT-2"
                          quantity: 2
                    -
                      order_id: "ORDER-437542111"
                      creation_date: "2016-03-30"
                      items:
                        -
                          product_id: "PRODUCT-7"
                          quantity: 6

```
