### ISSUE TITLE
Add validation - examples and example must be mutually exclusive 

### ISSUE THREAD

**Issue by eleonoraortega** [mulesoft-labs/rajapa#35]
The following definition is not validated:

``` yaml
dogAge:
   type: number
   examples:
     previous: 12
     current: 13
   example: 1
```

and it is parsed as follow:

``` json
"dogAge":  {
    "type": "number",
    "examples": {
        "previous": 12,
        "current": 13
    },
    "example": 1,
    "displayName": "dogAge"
}
```
