### ISSUE TITLE
Inheritance: Wrong validation when two types share same property

### ISSUE THREAD

**Issue by eleonoraortega** [mulesoft-labs/rajapa#36]
Using the following example:

``` yaml
#%RAML 1.0
title: My API With Types
types:
  Phone:
    type: object
    properties:
      manufacturer:
        type: string
      numberOfSIMCards:
        type: number
  Notebook:
    type: object
    properties:
      manufacturer:
        type: string
      numberOfUSBPorts:
        type: number
  Device:
    type: Phone | Notebook
    properties:
      weight: 
        type: number
```

The parser validates property 'manufacturer' and tries to merge properties from both types (Phone and Notebook) 

```
- property definition {manufacturer:string} overrides existing property: {manufacturer:string} [line=14, col=7] 
```
