### ISSUE TITLE
Example for Dates are not included in the output json

### ISSUE THREAD

**Issue by eleonoraortega** [mulesoft-labs/rajapa#41]
``` yaml
#%RAML 1.0
title: Example API

types:
  birthday:
    type: date-only # no implications about time or offset
    example: 2015-05-23
```

When using the previous example the output of the parser does not include the example:

```
{
    "title": "Example API",
    "types": {
        "birthday": {
            "type": "date-only",
            "example": {
            },
            "displayName": "birthday"
        }
    }
}
```
